parameters:
  exchange_rates_api_endpoint: 'https://exchangeratesapi.io'

services:
  _defaults:
    public: true

  invertus.ps_training.language.decorating_language_activator:
    class: 'Invertus\PsTraining\Language\DecoratingLanguageActivator'
    arguments:
      - '@invertus.ps_training.language.decorating_language_activator.inner'
      - '@prestashop.adapter.legacy.configuration'
    decorates: 'prestashop.adapter.language.activator'

  invertus.ps_training.currency.exchange_rates_currency_rate_updater:
    class: 'Invertus\PsTraining\Currency\ExchangeRatesCurrencyRateUpdater'
    arguments:
      - '%exchange_rates_api_endpoint%'
